package com.dragonblockinfinity.screen;

import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.components.Button;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

public class MenuInicial1 extends Screen {
    
        // ===== TEXTURAS =====
    ResourceLocation menuBase = new ResourceLocation("dragonblockinfinity", "textures/gui/menus/menu_base.png");
    ResourceLocation setaRight = new ResourceLocation("dragonblockinfinity", "textures/gui/buttoes/seta_right.png");
    ResourceLocation setaLeft = new ResourceLocation("dragonblockinfinity", "textures/gui/buttoes/seta_left.png");
                        
                            // ===== ESCOLHAS DO JOGADOR === 
    private int selectedTail = 0; // Qual cauda está selecionada
    private String[] tailTypes = {"Sayajin", "Arconsian"}; // Lista de caudas
                                        
                                            // ===== DIMENSÕES DO MENU =====
    private int menuWidth = 256;
    private int menuHeight = 200;
    private int menuX, menuY;

                                                                // ===== CONSTRUTOR (OBRIGATÓRIO!) =====
    public MenuInicial1() {
        super(Component.literal("Menu Inicial"));
    }

                      // ===== MÉTODO 1: INIT (criar botões) =====
                            @Override
                                protected void init() {
                                  super.init();
                                                                                                                
                                               // Centralizar o menu
                          this.menuX = (this.width - menuWidth) / 2;
                          this.menuY = (this.height - menuHeight) / 2;
                                                                                                                                                
                                        // DESAFIO 1: Criar os botões de seta aqui
                            // Dica: use addRenderableWidget(Button.builder(...))
                                                                    
                                            // idas:
                                   int setaY = menuY + 80; // Linha das setas
                                   int setaLeftX = menuX + 30;
                                   int setaRightX = menuX + 200;
                                                                                                                                                                                               
                                                   // ===== SETA ESQUERDA =====
                                  this.addRenderableWidget(Button.builder(
                                        Component.literal("<"),
                                         btn -> {
                                                                                                           // DESAFIO 2: Complete a lógica aqui
                                                                                                                                                                             // O que acontece quando clica na seta esquerda?
                                                                                                                                                                                                                                                                                selectedTail--;
                                                                                                                                                                                                                                                                                                                        if (selectedTail < 0) {
                                                                                                                                                                                                                                                                                                                                            selectedTail = tailTypes.length - 1;
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Cauda: " + tailTypes[selectedTail]);
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                ).bounds(setaLeftX, setaY, 20, 20).build());
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                // ===== SETA DIREITA =====
                                                                                                                                                                                                                                                                                                                                                                                                                        // DESAFIO 3: Faça você mesmo! Copie o de cima e mude pra direita
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                    // ===== MÉTODO 2: RENDER (desenhar na tela) =====
                                                                                                                                                                                                                                                                                                                                                                                                                                        @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                            public void render(GuiGraphics graphics, int mouseX, int mouseY, float partialTicks) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Fundo escuro
                                                                                                                                                                                                                                                                                                                                                                                                                                                            graphics.fill(0, 0, this.width, this.height, 0x77000000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Desenhar textura do menu base
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    graphics.blit(menuBase, menuX, menuY, 0, 0, menuWidth, menuHeight, menuWidth, menuHeight);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // DESAFIO 4: Desenhar o texto "CAUDA: Sayajin" no meio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            String texto = "CAUDA: " + tailTypes[selectedTail];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int textoWidth = this.font.width(texto);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int textoX = menuX + (menuWidth - textoWidth) / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int textoY = menuY + 85;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    graphics.drawString(this.font, texto, textoX, textoY, 0xFFFFFF);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Renderizar botões
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            super.render(graphics, mouseX, mouseY, partialTicks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public boolean isPauseScreen() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }